'use strict';
const {test,expect}=require('@playwright/test');
const now=Date.now();
function competitions(){return [{id:'classic:U',teamId:'TC',format:'classic',leagueName:'Classic League',teamName:'Classic Team',score:812,status:'live',rank:4,rankMovement:2,players:{completed:12,live:3,toPlay:6},updatedAt:now,action:{label:'Open team',page:'classic'}},...['C1','C2'].map((id,i)=>({id,teamId:'T'+id,format:'custom',leagueName:'Custom '+(i+1),teamName:'Custom Team '+(i+1),score:500+i,status:i?'scheduled':'live',rank:i+1,players:{completed:i,live:1,toPlay:20-i},matchup:{opponentName:'Opponent '+i,opponentScore:450+i},updatedAt:now-i,action:{label:'Open matchup',page:'custom',leagueId:id}})),...['D1','D2'].map((id,i)=>({id,teamId:'T'+id,format:'draft',leagueName:'Draft '+(i+1),teamName:'Draft Team '+(i+1),score:i?null:620,status:i?'scheduled':'live',rank:null,players:{completed:10,live:2,toPlay:9},draft:{phase:'draft',myTurn:!i},urgent:!i,updatedAt:now-i,action:{label:i?'Open team':'Draft now',page:'draft',leagueId:id}}))]}
const alerts={alerts:[{key:'draft-turn:D1',severity:'Critical',title:'Your Draft turn is ready',consequence:'Another coach is waiting.',context:'Draft 1 · Draft Team 1',eventTime:now,action:{label:'Draft now',page:'draft',leagueId:'D1'}},{key:'news:A',severity:'Action required',title:'Selected Player needs attention',consequence:'Ruled out before lockout.',context:'Classic Team',eventTime:now,action:{label:'Fix team',page:'teamnews'}}]};
const newsItems=[{id:'N1',type:'Confirmed injury/return',playerName:'Selected Player',club:'Sharks',summary:'Ruled out with a confirmed injury.',round:20,source:'NRL.com',sourceUrl:'https://www.nrl.com/',sourceTime:new Date(now).toISOString(),confirmation:'Confirmed',relevance:'My player'},{id:'N2',type:'Official team list named',playerName:'Watched Player',club:'Storm',summary:'Added to the starting side.',round:20,source:'NRL.com',sourceUrl:'https://www.nrl.com/',sourceTime:new Date(now-1000).toISOString(),confirmation:'Estimated',relevance:'Watchlist'}];
async function open(browser,width,{summaryFailure=false}={}){const context=await browser.newContext({baseURL:'http://127.0.0.1:32188',viewport:{width,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.route('**/api/soo/me',r=>r.fulfill({json:{userId:'U',name:'Home Coach',email:'home@example.test'}}));await page.route('**/api/app-state',r=>r.fulfill({json:r.request().method()==='GET'?{version:0,state:null}:{ok:true,version:1}}));await page.route('**/api/fantasy-leagues**',r=>r.fulfill({json:{leagues:[],limit:20}}));await page.route('**/api/home/summary',r=>summaryFailure?r.fulfill({status:503,json:{error:'Unavailable'}}):r.fulfill({json:{round:20,deadline:'2026-07-16T19:50:00+10:00',freshness:'current',updatedAt:new Date(now).toISOString(),actionCount:2,competitions:competitions()}}));await page.route('**/api/home/alerts',r=>r.fulfill({json:alerts}));await page.route('**/api/home/team-news**',r=>{const scope=new URL(r.request().url()).searchParams.get('scope'),items=scope==='watchlist'?newsItems.filter(x=>x.relevance==='Watchlist'):scope==='my-players'?newsItems.filter(x=>x.relevance==='My player'):newsItems;return r.fulfill({json:{items,nextCursor:null,since:null,freshness:'current',checkedAt:new Date(now).toISOString()}})});await page.goto('/');if(await page.getByText('Choose your look').isVisible().catch(()=>false)){await page.getByRole('button',{name:'Electric Blue'}).click();await page.getByRole('button',{name:'Skip tour'}).click()}await page.evaluate(()=>{S.settings.onboardingVersion=1;S.settings.themeChosen=true;closeModal();setPage('home')});await expect(page.getByRole('heading',{name:'Home',level:1})).toBeVisible();return {context,page,errors}}

test('Home command centre separates alerts, competitions and news without the Classic player duplicate',async({browser})=>{const {context,page,errors}=await open(browser,1440);await expect(page.locator('.home-competition')).toHaveCount(5);await expect(page.locator('[data-competition-id="C1"]')).toContainText('Custom 1');await expect(page.locator('[data-competition-id="C2"]')).toContainText('501');await expect(page.getByText('Your Draft turn is ready')).toBeVisible();await expect(page.locator('.home-news-item')).toHaveCount(1);await expect(page.locator('#home-alerts')).not.toContainText('Official team list named');await expect(page.locator('#pg-home')).not.toContainText('Live player scores');await page.getByRole('tab',{name:'Watchlist'}).click();await expect(page.getByText('Watched Player')).toBeVisible();await page.getByRole('tab',{name:'All teams'}).click();await expect(page.locator('.home-news-item')).toHaveCount(2);expect(errors).toEqual([]);await context.close()});

test('critical alerts stay visible when acknowledged while safe alerts dismiss',async({browser})=>{const {context,page}=await open(browser,1024);await page.getByRole('button',{name:'Acknowledge'}).click();await expect(page.getByText('Your Draft turn is ready')).toBeVisible();await page.getByRole('button',{name:'Dismiss'}).click();await expect(page.getByText('Selected Player needs attention')).toBeHidden();await context.close()});

test('Home remains responsive and accessible at every width, theme, zoom and reduced motion',async({browser})=>{for(const width of [320,375,390,768,1024,1440,1920]){const {context,page,errors}=await open(browser,width);await expect(page.locator('.home-competition').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth),width+' overflow').toBeLessThanOrEqual(1);if(width<=768){const targets=await page.locator('#pg-home button:visible').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().height));expect(Math.min(...targets)).toBeGreaterThanOrEqual(40)}for(const theme of ['lime','blue','gold','coral'])await page.evaluate(value=>applyTheme(value,false),theme);await page.evaluate(()=>document.documentElement.style.zoom='2');expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(errors).toEqual([]);await context.close()}});

test('one failed Home section does not block alerts, news or navigation',async({browser})=>{const {context,page}=await open(browser,390,{summaryFailure:true});await expect(page.getByText('Your Draft turn is ready')).toBeVisible();await expect(page.getByText('Selected Player',{exact:false}).first()).toBeVisible();await page.evaluate(()=>setPage('players'));await expect(page.getByRole('heading',{name:'Players',level:1})).toBeVisible();await context.close()});
