'use strict';
const {test,expect}=require('@playwright/test');
const now=Date.now();
function competitions(){return [{id:'classic:U',teamId:'TC',format:'classic',leagueName:'Classic League',teamName:'Classic Team',score:null,status:'scheduled',rank:4,players:{completed:12,live:3,toPlay:6},updatedAt:now,action:{label:'View team',page:'classic'}},{id:'C1',teamId:'TC1',format:'custom',leagueName:'Shared League',teamName:'Custom Team 1',score:null,status:'scheduled',urgent:true,updatedAt:now-1,action:{label:'View team',page:'custom',leagueId:'C1'}},{id:'C2',teamId:'TC2',format:'custom',leagueName:'Shared League',teamName:'Custom Team 2',score:824,status:'live',rank:2,players:{completed:10,live:7,toPlay:4},matchup:{opponentName:'Sharks',opponentScore:798},stale:true,updatedAt:now-2,action:{label:'View team',page:'custom',leagueId:'C2'}},{id:'D1',teamId:'TD1',format:'draft',leagueName:'Draft 1',teamName:'Draft Team 1',score:null,status:'scheduled',draft:{phase:'draft',myTurn:true,waiverDeadline:new Date(now+84*60000).toISOString()},urgent:true,updatedAt:now-3,action:{label:'Draft now',page:'draft',leagueId:'D1'}},{id:'D2',teamId:'TD2',format:'draft',leagueName:'Draft 2',teamName:'Draft Team 2',score:null,status:'scheduled',draft:{phase:'lobby',myTurn:false},updatedAt:now-4,action:{label:'View team',page:'draft',leagueId:'D2'}},{id:'origin:Q',teamId:'TO',format:'origin',leagueName:'QLD Greats',teamName:'Origin Team',score:null,status:'final',rank:2,updatedAt:now-5,action:{label:'View team',page:'origin'}}]}
const alerts={alerts:[{key:'draft-turn:D1',severity:'Critical',title:'Your Draft turn is ready',consequence:'Another coach is waiting.',context:'Draft 1 · Draft Team 1',eventTime:now,action:{label:'Draft now',page:'draft',leagueId:'D1'}},{key:'news:A',severity:'Action required',title:'Selected Player needs attention',consequence:'Ruled out before lockout.',context:'Classic Team',eventTime:now,action:{label:'Fix team',page:'teamnews'}}]};
const newsItems=[{id:'N1',type:'Confirmed injury/return',playerName:'Selected Player',club:'Sharks',summary:'Ruled out with a confirmed injury.',round:20,source:'NRL.com',sourceUrl:'https://www.nrl.com/',sourceTime:new Date(now).toISOString(),confirmation:'Confirmed',relevance:'My player'},{id:'N2',type:'Official team list named',playerName:'Watched Player',club:'Storm',summary:'Added to the starting side.',round:20,source:'NRL.com',sourceUrl:'https://www.nrl.com/',sourceTime:new Date(now-1000).toISOString(),confirmation:'Estimated',relevance:'Watchlist'}];
async function open(browser,width,{summaryFailure=false}={}){const context=await browser.newContext({baseURL:'http://127.0.0.1:32188',viewport:{width,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.route('**/api/soo/me',r=>r.fulfill({json:{userId:'U',name:'Home Coach',email:'home@example.test'}}));await page.route('**/api/app-state',r=>r.fulfill({json:r.request().method()==='GET'?{version:0,state:null}:{ok:true,version:1}}));await page.route('**/api/fantasy-leagues**',r=>r.fulfill({json:{leagues:[],limit:20}}));await page.route('**/api/home/summary',r=>summaryFailure?r.fulfill({status:503,json:{error:'Unavailable'}}):r.fulfill({json:{round:20,deadline:'2026-07-16T19:50:00+10:00',freshness:'current',updatedAt:new Date(now).toISOString(),actionCount:2,competitions:competitions()}}));await page.route('**/api/home/alerts',r=>r.fulfill({json:alerts}));await page.route('**/api/home/team-news**',r=>{const scope=new URL(r.request().url()).searchParams.get('scope'),items=scope==='watchlist'?newsItems.filter(x=>x.relevance==='Watchlist'):scope==='my-players'?newsItems.filter(x=>x.relevance==='My player'):newsItems;return r.fulfill({json:{items,nextCursor:null,since:null,freshness:'current',checkedAt:new Date(now).toISOString()}})});await page.goto('/');if(await page.getByText('Choose your look').isVisible().catch(()=>false)){await page.getByRole('button',{name:'Electric Blue'}).click();await page.getByRole('button',{name:'Skip tour'}).click()}await page.evaluate(()=>{S.settings.onboardingVersion=1;S.settings.themeChosen=true;closeModal();setPage('home')});await expect(page.locator('#pg-home')).toBeVisible();return {context,page,errors}}

test('compact competitions show four rows, preserve priority, and expand all six without filler',async({browser})=>{const {context,page,errors}=await open(browser,1440);const rows=page.locator('.home-competition-row');await expect(rows).toHaveCount(4);await expect(page.getByRole('button',{name:'Show all competitions'})).toHaveAttribute('aria-expanded','false');await expect(rows.first()).toHaveAttribute('data-competition-id','C1');await expect(page.locator('[data-competition-id="D1"]')).toBeVisible();await expect(page.locator('#home-competitions')).not.toContainText(/Awaiting lockout|No matchup|—/);await page.getByRole('button',{name:'Show all competitions'}).click();await expect(rows).toHaveCount(6);await expect(page.getByRole('button',{name:'Show fewer'})).toHaveAttribute('aria-expanded','true');await expect(page.locator('[data-competition-id="origin:Q"]')).toContainText('Final');await expect(page.locator('[data-competition-id="C2"]')).toContainText(/Live matchup|Stale|824–798/);await expect(page.locator('[data-competition-id="D2"]')).toContainText('Scheduled');await page.getByRole('button',{name:'Show fewer'}).click();await expect(rows).toHaveCount(4);expect(errors).toEqual([]);await context.close()});

test('every compact row keeps exact duplicate-name league and team destinations',async({browser})=>{const {context,page}=await open(browser,1440);await page.getByRole('button',{name:'Show all competitions'}).click();await page.evaluate(()=>{window._competitionDestinations=[];window.setPage=page=>_competitionDestinations.push({page});window.switchFantasyLeague=(page,id)=>_competitionDestinations.push({page,id})});for(const [id,teamId,leagueId] of [['classic:U','TC','classic:U'],['C1','TC1','C1'],['C2','TC2','C2'],['D1','TD1','D1'],['D2','TD2','D2'],['origin:Q','TO','origin:Q']]){const row=page.locator(`[data-competition-id="${id}"]`);await expect(row).toHaveAttribute('data-team-id',teamId);await expect(row).toHaveAttribute('data-league-id',leagueId);await expect(row.getByRole('button')).toHaveAttribute('aria-label',/.+ in .+ for .+/);await row.getByRole('button').click()}await expect(page.locator('[data-competition-id="C1"] h3')).toHaveText('Shared League');await expect(page.locator('[data-competition-id="C2"] h3')).toHaveText('Shared League');expect(await page.evaluate(()=>_competitionDestinations)).toEqual([{page:'classic'},{page:'custom',id:'C1'},{page:'custom',id:'C2'},{page:'draft',id:'D1'},{page:'draft',id:'D2'},{page:'origin'}]);await context.close()});

test('Home command centre still separates alerts and news from competitions',async({browser})=>{const {context,page,errors}=await open(browser,1440);await expect(page.getByText('Your Draft turn is ready')).toBeVisible();await expect(page.locator('.home-news-item')).toHaveCount(1);await expect(page.locator('#home-alerts')).not.toContainText('Official team list named');await expect(page.locator('#pg-home')).not.toContainText('Live player scores');await page.getByRole('tab',{name:'Watchlist'}).click();await expect(page.getByText('Watched Player')).toBeVisible();await page.getByRole('tab',{name:'All teams'}).click();await expect(page.locator('.home-news-item')).toHaveCount(2);expect(errors).toEqual([]);await context.close()});

test('critical alerts stay visible when acknowledged while safe alerts dismiss',async({browser})=>{const {context,page}=await open(browser,1024);await page.getByRole('button',{name:'Acknowledge'}).click();await expect(page.getByText('Your Draft turn is ready')).toBeVisible();await page.getByRole('button',{name:'Dismiss'}).click();await expect(page.getByText('Selected Player needs attention')).toBeHidden();await context.close()});

test('Home remains responsive and accessible at every width, theme, zoom and reduced motion',async({browser})=>{for(const width of [320,375,390,768,1024,1440,1920]){const {context,page,errors}=await open(browser,width);await expect(page.locator('.home-competition').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth),width+' overflow').toBeLessThanOrEqual(1);if(width<=768){const targets=await page.locator('#home-competitions button:visible').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().height));expect(Math.min(...targets)).toBeGreaterThanOrEqual(44)}for(const theme of ['lime','blue','gold','coral'])await page.evaluate(value=>applyTheme(value,false),theme);await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>document.documentElement.style.zoom='2');expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(errors).toEqual([]);await context.close()}});

test('one failed Home section does not block alerts, news or navigation',async({browser})=>{const {context,page}=await open(browser,390,{summaryFailure:true});await expect(page.getByText('Your Draft turn is ready')).toBeVisible();await expect(page.getByText('Selected Player',{exact:false}).first()).toBeVisible();await page.evaluate(()=>setPage('players'));await expect(page.getByRole('heading',{name:'Players',level:1})).toBeVisible();await context.close()});
