'use strict';
const {test,expect}=require('@playwright/test');
const roundContext={season:2026,currentRound:20,liveRound:20,lastCompletedRound:19,state:'live',firstLockout:'2026-07-16T19:50:00+10:00',nextLockout:'2026-07-17T18:00:00+10:00',games:{complete:2,live:1,toPlay:5,total:8},updatedAt:new Date().toISOString(),cacheAgeMs:1000,stale:false,fixtures:[{id:1,status:'live',homeSquadId:1,awaySquadId:2,homeScore:18,awayScore:10}],appearances:[1,2]};
async function open(browser,width=1440){const context=await browser.newContext({baseURL:'http://127.0.0.1:32188',viewport:{width,height:width<500?844:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});await page.route('**/api/soo/me',route=>route.fulfill({json:{userId:'NAV',name:'Navigation Coach',email:'nav@example.test'}}));await page.route('**/api/app-state',route=>route.fulfill({json:route.request().method()==='GET'?{version:1,state:null}:{ok:true,version:2}}));await page.route('**/api/fantasy-leagues**',route=>route.fulfill({json:{leagues:[],limit:20}}));await page.route('**/api/round-context',route=>route.fulfill({json:roundContext}));await page.route('**/api/home/summary',route=>route.fulfill({json:{round:20,deadline:roundContext.nextLockout,roundContext,actionCount:0,competitions:[]}}));await page.route('**/api/home/alerts',route=>route.fulfill({json:{alerts:[]}}));await page.route('**/api/home/team-news**',route=>route.fulfill({json:{items:[],freshness:'current',checkedAt:new Date().toISOString()}}));await page.goto('/');await page.evaluate(()=>{S.settings.onboardingVersion=1;S.settings.themeChosen=true;closeModal()});return {context,page,errors}}

test('desktop and mobile navigation use the exact approved destinations and team selector',async({browser})=>{for(const width of [1440,390]){const {context,page,errors}=await open(browser,width);if(width===1440){expect(await page.locator('#sidebar-nav .navitem').allTextContents()).toEqual(['⌂Home','♙Classic','◇Custom','▤Draft','♧Leagues','◈Match Centre','◎Players','✚Team News']);await expect(page.locator('.sidebar-settings')).toHaveText(/Settings & Help/);await expect(page.locator('#sidebar-nav')).not.toContainText('State of Origin')}else{expect((await page.locator('#bottom-tabbar .btab').allTextContents()).map(value=>value.replace(/[⌂♧◈◎✚]/g,'').trim())).toEqual(['Home','Leagues','Match Centre','Players','Team News']);await page.evaluate(()=>setPage('home'));await expect(page.locator('.page.on .team-mode-selector')).toBeVisible();expect(await page.locator('.page.on .team-mode-selector button').allTextContents()).toEqual(['Classic','Custom','Draft'])}expect(errors).toEqual([]);await context.close()}});

test('verified Round 20 context overrides stale saved Round 19 across Home and team views',async({browser})=>{const {context,page}=await open(browser);await page.evaluate(()=>{S.round=19;return autoRefresh()});await page.evaluate(()=>setPage('home'));await expect(page.locator('.home-round-strip')).toContainText('Round 20');for(const destination of ['classic','custom','draft']){await page.evaluate(page=>setPage(page),destination);await expect(page.locator('.page.on .team-mode-selector')).toBeVisible();if(destination==='classic')await expect(page.locator('#pg-classic')).toContainText('Round 20')}await context.close()});

test('official live component modal groups contributions and reports reconciliation without averages',async({browser})=>{const {context,page}=await open(browser);await page.evaluate(()=>{S.round=20;LIVE={round:20,status:'live',fetched:Date.now(),scores:{0:25},matches:[{home:PLAYERS[0].sq,away:999,status:'live'}],kickoffs:{}};RST[0]=RST[0]||{};const st=Array(STAT_KEYS.length+1).fill(0);st[STAT_KEYS.indexOf('T')]=2;st[STAT_KEYS.indexOf('MT')]=3;st[STAT_KEYS.indexOf('TCK')]=10;st[24]=80;RST[0][20]=st;showStatLine(0,20,true)});await expect(page.locator('#modal')).toContainText('Scoring');await expect(page.locator('#modal')).toContainText('Defence');await expect(page.locator('#modal')).toContainText('Component reconciliation pending');await expect(page.locator('#modal')).not.toContainText('season average');await context.close()});

test('autosave exposes saving, saved, failure and stale-write conflict states',async({browser})=>{const {context,page}=await open(browser);await page.evaluate(()=>setTeamSaveStatus('saving','Saving...'));await expect(page.locator('#team-save-status')).toHaveText('Saving...');await page.evaluate(()=>setTeamSaveStatus('saved','Saved 9:27 pm'));await expect(page.locator('#team-save-status')).toContainText('Saved');await page.evaluate(()=>setTeamSaveStatus('failed','Save failed - Retry'));await expect(page.locator('#team-save-status')).toHaveText('Save failed - Retry');await page.evaluate(()=>setTeamSaveStatus('conflict','Save conflict - Reload'));await expect(page.locator('#team-save-status')).toHaveText('Save conflict - Reload');await context.close()});
