'use strict';
const {test,expect}=require('@playwright/test');

async function openLivePage(browser,width=1440){
  const context=await browser.newContext({baseURL:'http://127.0.0.1:32188',viewport:{width,height:900}}),page=await context.newPage(),writes=[],errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
  await page.route('**/api/**',route=>{const method=route.request().method();if(!['GET','HEAD'].includes(method))writes.push(`${method} ${route.request().url()}`);if(route.request().url().includes('/api/soo/me'))return route.fulfill({json:{userId:'LIVE',name:'Live Coach',email:'live@example.test'}});if(route.request().url().includes('/api/app-state'))return route.fulfill({json:{version:0,state:null}});if(route.request().url().includes('/api/fantasy-leagues'))return route.fulfill({json:{leagues:[]}});return route.continue()});
  await page.goto('/');
  await page.evaluate(()=>{S.settings.onboardingVersion=1;S.settings.themeChosen=true;closeModal()});
  return {context,page,writes,errors};
}

async function installFixture(page){return page.evaluate(()=>{
  S.round=20;S.season.rounds[20]={byes:[]};
  const used=new Set(),line=emptyLine();
  for(const [posId,count] of FIELD_STRUCT){const ids=PLAYERS.filter(player=>player.pos.includes(posId)&&!used.has(player.id)).slice(0,count).map(player=>player.id);line.starters[posId]=ids;ids.forEach(id=>used.add(id))}
  line.bench=PLAYERS.filter(player=>!used.has(player.id)).slice(0,4).map(player=>player.id);line.bench.forEach(id=>used.add(id));
  line.res=PLAYERS.filter(player=>!used.has(player.id)).slice(0,4).map(player=>player.id);line.c=line.starters[1][0];line.vc=line.starters[2][0];
  const selected=teamLineupPlayers(line).map(item=>item.pid),clubs=[...new Set(selected.map(id=>PLAYERS[id].sq))];
  LIVE={round:20,status:'live',fetched:Date.now(),scores:{},matches:clubs.map((club,index)=>({home:club,away:-index-1,status:index===0?'complete':index===1?'scheduled':'live'}))};
  selected.forEach((id,index)=>{const match=liveMatchForPlayer(id);if(match.status!=='scheduled'&&!(match.status==='complete'&&index===0))LIVE.scores[id]=index===1?0:10+index});
  return {line,selected,c:line.c,vc:line.vc,scheduled:selected.find(id=>liveMatchForPlayer(id).status==='scheduled'),live:selected.find(id=>liveMatchForPlayer(id).status==='live'),dnp:selected.find(id=>liveMatchForPlayer(id).status==='complete')};
})}

test('canonical live scores distinguish scheduled, live zero, final/DNP and match Match Centre',async({browser})=>{const {context,page,errors}=await openLivePage(browser);const fixture=await installFixture(page);const result=await page.evaluate(({scheduled,live,dnp})=>{LIVE.scores[live]=0;return {scheduled:canonicalPlayerScore(scheduled,20),live:canonicalPlayerScore(live,20),dnp:canonicalPlayerScore(dnp,20),mc:mcPts(live,20)}},fixture);expect(result.scheduled).toMatchObject({score:null,state:'YET TO PLAY'});expect(result.live).toMatchObject({score:0,state:'LIVE'});expect(result.dnp).toMatchObject({score:null,state:'DNP'});expect(result.mc).toBe(0);expect(errors).toEqual([]);await context.close()});

test('captain, vice captain, bench and emergencies obey the explicit competition rules',async({browser})=>{const {context,page}=await openLivePage(browser);const fixture=await installFixture(page);const totals=await page.evaluate(({line,c,vc})=>{LIVE.matches=LIVE.matches.map(match=>({...match,status:'live'}));teamLineupPlayers(line).forEach(({pid},index)=>LIVE.scores[pid]=10+index);LIVE.scores[c]=40;LIVE.scores[vc]=30;const classic=liveLineupScore(line,{settings:{captainMult:2,benchScores:false}});const custom=liveLineupScore(line,{settings:{captainMult:3,benchScores:true}});delete LIVE.scores[c];const club=PLAYERS[c].sq;LIVE.matches=LIVE.matches.map(match=>match.home===club?{...match,status:'complete'}:match);const fallback=liveLineupScore(line,{settings:{captainMult:2,benchScores:false}});return {classic:classic.total,custom:custom.total,fallback:fallback.total,vcApplied:fallback.detail.find(item=>item.pid===vc)?.multiplier,classicCount:classic.detail.length,customCount:custom.detail.length}},fixture);expect(totals.custom).toBeGreaterThan(totals.classic);expect(totals.vcApplied).toBe(2);expect(totals.customCount).toBe(totals.classicCount+fixture.line.bench.length);expect(totals.fallback).toBeGreaterThan(0);await context.close()});

test('Classic, two Custom and two Draft contexts share raw scores but retain isolated totals',async({browser})=>{const {context,page}=await openLivePage(browser);const fixture=await installFixture(page);const result=await page.evaluate(({line,live})=>{LIVE.matches=LIVE.matches.map(match=>({...match,status:'live'}));teamLineupPlayers(line).forEach(({pid},index)=>LIVE.scores[pid]=20+index);const second=structuredClone(line),swap=second.starters[6][0];second.starters[6][0]=second.bench[0];second.bench[0]=swap;const contexts=[liveLineupScore(line,{settings:{captainMult:2,benchScores:false}}),liveLineupScore(line,{settings:{captainMult:3,benchScores:false}}),liveLineupScore(second,{settings:{captainMult:2,benchScores:true}}),liveLineupScore(line,{settings:{captainMult:1.5},draft:true}),liveLineupScore(second,{settings:{captainMult:2},draft:true})];return {raw:contexts.map(score=>canonicalPlayerScore(live,20).score),totals:contexts.map(score=>score.total),unchanged:line.starters[6][0]!==second.starters[6][0]}},fixture);expect(new Set(result.raw).size).toBe(1);expect(new Set(result.totals).size).toBeGreaterThan(2);expect(result.unchanged).toBe(true);await context.close()});

test('prominent panel covers lifecycle, corrections, stale state and independent league totals',async({browser})=>{const {context,page}=await openLivePage(browser);const fixture=await installFixture(page);const states=await page.evaluate(({line,live})=>{const mount=document.createElement('div');document.body.append(mount);const draw=(settings={captainMult:2,benchScores:false})=>{mount.innerHTML=teamScorePanelHTML('classic',line,{settings});return mount.textContent};LIVE.status='scheduled';const before=draw();LIVE.status='live';const liveText=draw();const first=liveLineupScore(line,{settings:{captainMult:2,benchScores:false}}).total;LIVE.scores[live]+=17;refreshLivePage();const corrected=liveLineupScore(line,{settings:{captainMult:2,benchScores:false}}).total;_refreshFailures=1;const stale=draw();_refreshFailures=0;LIVE.status='final';const provisional=draw();const a=liveLineupScore(line,{settings:{captainMult:2,benchScores:false}}).total,b=liveLineupScore(line,{settings:{captainMult:3,benchScores:true}}).total;return {before,liveText,first,corrected,stale,provisional,a,b}},fixture);expect(states.before).toContain('Score available after lockout');expect(states.before).not.toContain('Provisional score0');expect(states.liveText).toContain('Provisional score');expect(states.liveText).toContain('Completed');expect(states.liveText).toContain('Playing now');expect(states.liveText).toContain('To play');expect(states.corrected).toBe(states.first+17);expect(states.stale).toContain('Stale');expect(states.provisional).toMatch(/Provisional final|Final score/);expect(states.a).not.toBe(states.b);await context.close()});

test('mobile sticky summary is unobscured, accessible, theme-safe and passive refresh sends no writes',async({browser})=>{const {context,page,writes,errors}=await openLivePage(browser,390);const fixture=await installFixture(page);await page.evaluate(line=>{S.classic.line=line;S.classic.history[20]=line;S.ui.page='classic';renderClassic()},fixture.line);const panel=page.locator('.team-live-score-panel');await expect(panel).toBeVisible();await expect(panel).toHaveCSS('position','sticky');await panel.locator('summary').click();await expect(panel.locator('details')).toHaveAttribute('open','');await page.evaluate(()=>{document.getElementById('pg-classic').style.minHeight='2400px';scrollTo(0,500);refreshLivePage()});await page.waitForTimeout(100);expect(await page.evaluate(()=>scrollY)).toBeGreaterThan(300);await expect(panel.locator('details')).toHaveAttribute('open','');for(const theme of ['lime','blue','gold','coral'])await page.evaluate(value=>applyTheme(value,false),theme);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);expect(writes).toEqual([]);expect(errors).toEqual([]);await context.close()});
